# $FreeBSD$

PORTREVISION=   0
CATEGORIES= sysutils
PKGNAMESUFFIX?=	-cli

MAINTAINER=		y@trombik.org
COMMENT=		Distributed applications monitoring, CLI tools only

LICENSE=		APACHE20

OPTIONS_SLAVE=  SENSU_CLI
MASTERDIR=	${.CURDIR}/../sensu-go

.include "${MASTERDIR}/Makefile"
